ALTER TABLE public.vagas ADD COLUMN IF NOT EXISTS lead TEXT;
ALTER TABLE public.vagas ADD COLUMN IF NOT EXISTS local_trabalho TEXT;
ALTER TABLE public.vagas ADD COLUMN IF NOT EXISTS linha TEXT;
ALTER TABLE public.vagas ADD COLUMN IF NOT EXISTS vinculo TEXT;
ALTER TABLE public.vagas ADD COLUMN IF NOT EXISTS modalidade TEXT;
ALTER TABLE public.vagas ADD COLUMN IF NOT EXISTS pcd BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE public.vagas ADD COLUMN IF NOT EXISTS inscricoes_ate DATE;
ALTER TABLE public.vagas ADD COLUMN IF NOT EXISTS responsabilidades TEXT;
ALTER TABLE public.vagas ADD COLUMN IF NOT EXISTS requisitos TEXT;
ALTER TABLE public.vagas ADD COLUMN IF NOT EXISTS informacoes TEXT;
ALTER TABLE public.vagas ADD COLUMN IF NOT EXISTS etapas TEXT;
ALTER TABLE public.vagas ADD COLUMN IF NOT EXISTS links JSONB;
ALTER TABLE public.vagas ADD COLUMN IF NOT EXISTS ativa BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE public.vagas ADD COLUMN IF NOT EXISTS publicada_em TIMESTAMPTZ NOT NULL DEFAULT now();

CREATE TABLE IF NOT EXISTS public.rh_site_config (
  empresa TEXT PRIMARY KEY,
  etapas_padrao TEXT,
  sobre_ibmf TEXT,
  updated_by TEXT,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
